services:
    webstore.product_repository:
        class: WebstoreBundle\Entity\ProductRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["WebstoreBundle:Product"]

    webstore.customer_repository:
        class: WebstoreBundle\Entity\CustomerRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: ["WebstoreBundle:Customer"]